# Generated by Django 4.2.1 on 2023-05-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='has_it_completed',
            new_name='has_it_competed',
        ),
    ]
